log_dir: "./log"

task_queue:
    max_workers: 1
    max_buffer: 1024

tasks:
    - type: "cmd"
      name: "python"
      args: ["say.py","-f -t limitedfree -l cn -p"]
      output: "stdout"
      duration: 10 #seconds
    - type: "cmd"
      name: "echo"
      args: ["hello again"]
      output: "stdout"
      duration: 20 #seconds