log_dir: "./log"

task_queue:
    max_workers: 1
    max_buffer: 1024

tasks:
    - type: "cmd"
      name: "echo"
      args: ["hello","world"]
      output: "file"
      output_file: "./1.log"
      duration: 10 #seconds
    - type: "cmd"
      name: "echo"
      args: ["hello again"]
      output: "stdout"
      duration: 4 #seconds
